routes:
  - name: home
    composable: Baka
  - name: latestFiles
    composable: LatestFiles
  - name: fileEditor
    composable: FileEditorWindow
    params:
      - filePath
  - name: settings
    composable: SettingsPage
startup: home
